-- Auto-generated Phase 4 seed for MOCK12. Run after phase1_migration_mock12.sql.
USE [Hacienda_ERP_Test];
GO
SET NOCOUNT ON;
GO

-- VALIDATION_GROUPS_MOCK12 ---------------------------------------
DELETE FROM VALIDATION_GROUPS_MOCK12;
INSERT INTO VALIDATION_GROUPS_MOCK12 (Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module, Data_Entity,  Members_Total, Members_Currently_Loaded, All_Members_Loaded,  Error_Threshold, Threshold_Exceeded, Reextract_Required,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'APINV-PRIFAS', N'AP Invoices — PRIFAS Sources', N'MOCK12', N'FIN', N'AP', N'AP Invoices', 2, 0, N'N',0, N'N', N'N', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VALIDATION_GROUPS_MOCK12 (Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module, Data_Entity,  Members_Total, Members_Currently_Loaded, All_Members_Loaded,  Error_Threshold, Threshold_Exceeded, Reextract_Required,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'SUP-PRIFAS', N'Suppliers — PRIFAS Sources', N'MOCK12', N'FIN', N'AP', N'Suppliers', 6, 0, N'N',50, N'N', N'N', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VALIDATION_GROUPS_MOCK12 (Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module, Data_Entity,  Members_Total, Members_Currently_Loaded, All_Members_Loaded,  Error_Threshold, Threshold_Exceeded, Reextract_Required,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'APINV-911', N'AP Invoices — 911', N'MOCK12', N'FIN', N'AP', N'AP Invoices', 0, 0, N'N',0, N'N', N'N', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VALIDATION_GROUPS_MOCK12 (Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module, Data_Entity,  Members_Total, Members_Currently_Loaded, All_Members_Loaded,  Error_Threshold, Threshold_Exceeded, Reextract_Required,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'APINV-ASSMCA', N'AP Invoices — ASSMCA', N'MOCK12', N'FIN', N'AP', N'AP Invoices', 0, 0, N'N',0, N'N', N'N', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VALIDATION_GROUPS_MOCK12 (Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module, Data_Entity,  Members_Total, Members_Currently_Loaded, All_Members_Loaded,  Error_Threshold, Threshold_Exceeded, Reextract_Required,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'APINV-FIMAS', N'AP Invoices — FIMAS', N'MOCK12', N'FIN', N'AP', N'AP Invoices', 0, 0, N'N',0, N'N', N'N', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VALIDATION_GROUPS_MOCK12 (Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module, Data_Entity,  Members_Total, Members_Currently_Loaded, All_Members_Loaded,  Error_Threshold, Threshold_Exceeded, Reextract_Required,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'APINV-HACIENDA', N'AP Invoices — HACIENDA', N'MOCK12', N'FIN', N'AP', N'AP Invoices', 0, 0, N'N',0, N'N', N'N', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VALIDATION_GROUPS_MOCK12 (Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module, Data_Entity,  Members_Total, Members_Currently_Loaded, All_Members_Loaded,  Error_Threshold, Threshold_Exceeded, Reextract_Required,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'APINV-SALUD', N'AP Invoices — SALUD', N'MOCK12', N'FIN', N'AP', N'AP Invoices', 0, 0, N'N',0, N'N', N'N', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VALIDATION_GROUPS_MOCK12 (Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module, Data_Entity,  Members_Total, Members_Currently_Loaded, All_Members_Loaded,  Error_Threshold, Threshold_Exceeded, Reextract_Required,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'APINV-SIFDE', N'AP Invoices — SIFDE', N'MOCK12', N'FIN', N'AP', N'AP Invoices', 0, 0, N'N',0, N'N', N'N', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VALIDATION_GROUPS_MOCK12 (Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module, Data_Entity,  Members_Total, Members_Currently_Loaded, All_Members_Loaded,  Error_Threshold, Threshold_Exceeded, Reextract_Required,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'BPA-ASSMCA', N'Blanket Purchase Agreements — ASSMCA', N'MOCK12', N'FIN', N'AP', N'Blanket Purchase Agreements', 0, 0, N'N',0, N'N', N'N', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VALIDATION_GROUPS_MOCK12 (Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module, Data_Entity,  Members_Total, Members_Currently_Loaded, All_Members_Loaded,  Error_Threshold, Threshold_Exceeded, Reextract_Required,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'BPA-FIMAS', N'Blanket Purchase Agreements — FIMAS', N'MOCK12', N'FIN', N'AP', N'Blanket Purchase Agreements', 0, 0, N'N',0, N'N', N'N', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VALIDATION_GROUPS_MOCK12 (Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module, Data_Entity,  Members_Total, Members_Currently_Loaded, All_Members_Loaded,  Error_Threshold, Threshold_Exceeded, Reextract_Required,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'BPA-HACIENDA', N'Blanket Purchase Agreements — HACIENDA', N'MOCK12', N'FIN', N'AP', N'Blanket Purchase Agreements', 0, 0, N'N',0, N'N', N'N', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VALIDATION_GROUPS_MOCK12 (Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module, Data_Entity,  Members_Total, Members_Currently_Loaded, All_Members_Loaded,  Error_Threshold, Threshold_Exceeded, Reextract_Required,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'BPA-PRIFAS', N'Blanket Purchase Agreements — PRIFAS', N'MOCK12', N'FIN', N'AP', N'Blanket Purchase Agreements', 0, 0, N'N',0, N'N', N'N', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VALIDATION_GROUPS_MOCK12 (Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module, Data_Entity,  Members_Total, Members_Currently_Loaded, All_Members_Loaded,  Error_Threshold, Threshold_Exceeded, Reextract_Required,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'BPA-SALUD', N'Blanket Purchase Agreements — SALUD', N'MOCK12', N'FIN', N'AP', N'Blanket Purchase Agreements', 0, 0, N'N',0, N'N', N'N', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VALIDATION_GROUPS_MOCK12 (Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module, Data_Entity,  Members_Total, Members_Currently_Loaded, All_Members_Loaded,  Error_Threshold, Threshold_Exceeded, Reextract_Required,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'BPA-SIFDE', N'Blanket Purchase Agreements — SIFDE', N'MOCK12', N'FIN', N'AP', N'Blanket Purchase Agreements', 0, 0, N'N',0, N'N', N'N', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VALIDATION_GROUPS_MOCK12 (Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module, Data_Entity,  Members_Total, Members_Currently_Loaded, All_Members_Loaded,  Error_Threshold, Threshold_Exceeded, Reextract_Required,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'CONT-SIFDE', N'Contracts — SIFDE', N'MOCK12', N'FIN', N'AP', N'Contracts', 0, 0, N'N',0, N'N', N'N', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VALIDATION_GROUPS_MOCK12 (Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module, Data_Entity,  Members_Total, Members_Currently_Loaded, All_Members_Loaded,  Error_Threshold, Threshold_Exceeded, Reextract_Required,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'PO-911', N'Purchase Orders — 911', N'MOCK12', N'FIN', N'AP', N'Purchase Orders', 0, 0, N'N',0, N'N', N'N', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VALIDATION_GROUPS_MOCK12 (Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module, Data_Entity,  Members_Total, Members_Currently_Loaded, All_Members_Loaded,  Error_Threshold, Threshold_Exceeded, Reextract_Required,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'PO-ASSMCA', N'Purchase Orders — ASSMCA', N'MOCK12', N'FIN', N'AP', N'Purchase Orders', 0, 0, N'N',0, N'N', N'N', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VALIDATION_GROUPS_MOCK12 (Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module, Data_Entity,  Members_Total, Members_Currently_Loaded, All_Members_Loaded,  Error_Threshold, Threshold_Exceeded, Reextract_Required,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'PO-FIMAS', N'Purchase Orders — FIMAS', N'MOCK12', N'FIN', N'AP', N'Purchase Orders', 0, 0, N'N',0, N'N', N'N', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VALIDATION_GROUPS_MOCK12 (Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module, Data_Entity,  Members_Total, Members_Currently_Loaded, All_Members_Loaded,  Error_Threshold, Threshold_Exceeded, Reextract_Required,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'PO-HACIENDA', N'Purchase Orders — HACIENDA', N'MOCK12', N'FIN', N'AP', N'Purchase Orders', 0, 0, N'N',0, N'N', N'N', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VALIDATION_GROUPS_MOCK12 (Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module, Data_Entity,  Members_Total, Members_Currently_Loaded, All_Members_Loaded,  Error_Threshold, Threshold_Exceeded, Reextract_Required,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'PO-PRIFAS', N'Purchase Orders — PRIFAS', N'MOCK12', N'FIN', N'AP', N'Purchase Orders', 0, 0, N'N',0, N'N', N'N', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VALIDATION_GROUPS_MOCK12 (Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module, Data_Entity,  Members_Total, Members_Currently_Loaded, All_Members_Loaded,  Error_Threshold, Threshold_Exceeded, Reextract_Required,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'PO-SALUD', N'Purchase Orders — SALUD', N'MOCK12', N'FIN', N'AP', N'Purchase Orders', 0, 0, N'N',0, N'N', N'N', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VALIDATION_GROUPS_MOCK12 (Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module, Data_Entity,  Members_Total, Members_Currently_Loaded, All_Members_Loaded,  Error_Threshold, Threshold_Exceeded, Reextract_Required,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'PO-SIFDE', N'Purchase Orders — SIFDE', N'MOCK12', N'FIN', N'AP', N'Purchase Orders', 0, 0, N'N',0, N'N', N'N', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VALIDATION_GROUPS_MOCK12 (Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module, Data_Entity,  Members_Total, Members_Currently_Loaded, All_Members_Loaded,  Error_Threshold, Threshold_Exceeded, Reextract_Required,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'PROCONT-ASG', N'Procurement Contracts — ASG', N'MOCK12', N'FIN', N'AP', N'Procurement Contracts', 0, 0, N'N',0, N'N', N'N', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VALIDATION_GROUPS_MOCK12 (Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module, Data_Entity,  Members_Total, Members_Currently_Loaded, All_Members_Loaded,  Error_Threshold, Threshold_Exceeded, Reextract_Required,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'REQ-SIFDE', N'Requisition — SIFDE', N'MOCK12', N'FIN', N'AP', N'Requisition', 0, 0, N'N',0, N'N', N'N', N'phase4_seed', SYSUTCDATETIME());
PRINT 'Seeded 24 VALIDATION_GROUPS_MOCK12 rows';
GO

-- VBL_GROUPS_MOCK12 ----------------------------------------------
DELETE FROM VBL_GROUPS_MOCK12;
INSERT INTO VBL_GROUPS_MOCK12 (VBL_Group_ID, VBL_Group_Name, Mock_Number, Pillar, Module,  Val_To_Source_Members_Total, Val_To_Source_Members_Approved, All_Val_To_Source_Approved,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'VBL-FIN-AP', N'FIN Accounts Payable — Before Load Validation', N'MOCK12', N'FIN', N'AP', 2, 0, N'N',N'phase4_seed', SYSUTCDATETIME());
PRINT 'Seeded 1 VBL_GROUPS_MOCK12 rows';
GO

-- VBL_GROUP_MEMBERS_MOCK12 ---------------------------------------
DELETE FROM VBL_GROUP_MEMBERS_MOCK12;
INSERT INTO VBL_GROUP_MEMBERS_MOCK12 (VBL_Group_ID, Validation_Group_ID, Required, Blocks_VBL_Trigger,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'VBL-FIN-AP', N'APINV-PRIFAS', N'Y', N'Y', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VBL_GROUP_MEMBERS_MOCK12 (VBL_Group_ID, Validation_Group_ID, Required, Blocks_VBL_Trigger,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'VBL-FIN-AP', N'SUP-PRIFAS', N'Y', N'Y', N'phase4_seed', SYSUTCDATETIME());
PRINT 'Seeded 2 VBL_GROUP_MEMBERS_MOCK12 rows';
GO

-- VG_DEPENDENCIES_MOCK12 -----------------------------------------
DELETE FROM VG_DEPENDENCIES_MOCK12;
INSERT INTO VG_DEPENDENCIES_MOCK12 (Dependency_ID, Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module,  Depends_On_Table_Name, Depends_On_Validation_Group_ID, Dependency_Reason,  Dependency_Status, Blocks_Validation_Trigger,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'DEP-0001', N'APINV-911', N'AP Invoices — 911', N'MOCK12', N'FIN', N'AP', N'SCM_SUPPLIER_MOCK12_911', N'SUP-911', N'Supplier existence check — validations cross-reference supplier IDs against the Supplier header table to verify referenced suppliers exist', N'Not Loaded', N'Y', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VG_DEPENDENCIES_MOCK12 (Dependency_ID, Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module,  Depends_On_Table_Name, Depends_On_Validation_Group_ID, Dependency_Reason,  Dependency_Status, Blocks_Validation_Trigger,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'DEP-0002', N'APINV-ASSMCA', N'AP Invoices — ASSMCA', N'MOCK12', N'FIN', N'AP', N'SCM_SUPPLIER_MOCK12_ASSMCA', N'SUP-ASSMCA', N'Supplier existence check — validations cross-reference supplier IDs against the Supplier header table to verify referenced suppliers exist', N'Not Loaded', N'Y', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VG_DEPENDENCIES_MOCK12 (Dependency_ID, Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module,  Depends_On_Table_Name, Depends_On_Validation_Group_ID, Dependency_Reason,  Dependency_Status, Blocks_Validation_Trigger,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'DEP-0003', N'APINV-FIMAS', N'AP Invoices — FIMAS', N'MOCK12', N'FIN', N'AP', N'SCM_SUPPLIER_MOCK12_FIMAS', N'SUP-FIMAS', N'Supplier existence check — validations cross-reference supplier IDs against the Supplier header table to verify referenced suppliers exist', N'Not Loaded', N'Y', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VG_DEPENDENCIES_MOCK12 (Dependency_ID, Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module,  Depends_On_Table_Name, Depends_On_Validation_Group_ID, Dependency_Reason,  Dependency_Status, Blocks_Validation_Trigger,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'DEP-0004', N'APINV-HACIENDA', N'AP Invoices — HACIENDA', N'MOCK12', N'FIN', N'AP', N'SCM_SUPPLIER_MOCK12_HACIENDA', N'SUP-HACIENDA', N'Supplier existence check — validations cross-reference supplier IDs against the Supplier header table to verify referenced suppliers exist', N'Not Loaded', N'Y', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VG_DEPENDENCIES_MOCK12 (Dependency_ID, Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module,  Depends_On_Table_Name, Depends_On_Validation_Group_ID, Dependency_Reason,  Dependency_Status, Blocks_Validation_Trigger,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'DEP-0005', N'APINV-PRIFAS', N'AP Invoices — PRIFAS', N'MOCK12', N'FIN', N'AP', N'SCM_SUPPLIER_MOCK12_PRIFAS', N'SUP-PRIFAS', N'Supplier existence check — validations cross-reference supplier IDs against the Supplier header table to verify referenced suppliers exist', N'Not Loaded', N'Y', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VG_DEPENDENCIES_MOCK12 (Dependency_ID, Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module,  Depends_On_Table_Name, Depends_On_Validation_Group_ID, Dependency_Reason,  Dependency_Status, Blocks_Validation_Trigger,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'DEP-0006', N'APINV-SALUD', N'AP Invoices — SALUD', N'MOCK12', N'FIN', N'AP', N'SCM_SUPPLIER_MOCK12_SALUD', N'SUP-SALUD', N'Supplier existence check — validations cross-reference supplier IDs against the Supplier header table to verify referenced suppliers exist', N'Not Loaded', N'Y', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VG_DEPENDENCIES_MOCK12 (Dependency_ID, Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module,  Depends_On_Table_Name, Depends_On_Validation_Group_ID, Dependency_Reason,  Dependency_Status, Blocks_Validation_Trigger,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'DEP-0007', N'APINV-SIFDE', N'AP Invoices — SIFDE', N'MOCK12', N'FIN', N'AP', N'SCM_SUPPLIER_MOCK12_SIFDE', N'SUP-SIFDE', N'Supplier existence check — validations cross-reference supplier IDs against the Supplier header table to verify referenced suppliers exist', N'Not Loaded', N'Y', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VG_DEPENDENCIES_MOCK12 (Dependency_ID, Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module,  Depends_On_Table_Name, Depends_On_Validation_Group_ID, Dependency_Reason,  Dependency_Status, Blocks_Validation_Trigger,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'DEP-0008', N'BPA-ASSMCA', N'Blanket Purchase Agreements — ASSMCA', N'MOCK12', N'SCM', N'PO', N'SCM_SUPPLIER_MOCK12_ASSMCA', N'SUP-ASSMCA', N'Supplier existence check — validations cross-reference supplier IDs against the Supplier header table to verify referenced suppliers exist', N'Not Loaded', N'Y', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VG_DEPENDENCIES_MOCK12 (Dependency_ID, Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module,  Depends_On_Table_Name, Depends_On_Validation_Group_ID, Dependency_Reason,  Dependency_Status, Blocks_Validation_Trigger,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'DEP-0009', N'BPA-FIMAS', N'Blanket Purchase Agreements — FIMAS', N'MOCK12', N'SCM', N'PO', N'SCM_SUPPLIER_MOCK12_FIMAS', N'SUP-FIMAS', N'Supplier existence check — validations cross-reference supplier IDs against the Supplier header table to verify referenced suppliers exist', N'Not Loaded', N'Y', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VG_DEPENDENCIES_MOCK12 (Dependency_ID, Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module,  Depends_On_Table_Name, Depends_On_Validation_Group_ID, Dependency_Reason,  Dependency_Status, Blocks_Validation_Trigger,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'DEP-0010', N'BPA-HACIENDA', N'Blanket Purchase Agreements — HACIENDA', N'MOCK12', N'SCM', N'PO', N'SCM_SUPPLIER_MOCK12_HACIENDA', N'SUP-HACIENDA', N'Supplier existence check — validations cross-reference supplier IDs against the Supplier header table to verify referenced suppliers exist', N'Not Loaded', N'Y', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VG_DEPENDENCIES_MOCK12 (Dependency_ID, Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module,  Depends_On_Table_Name, Depends_On_Validation_Group_ID, Dependency_Reason,  Dependency_Status, Blocks_Validation_Trigger,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'DEP-0011', N'BPA-PRIFAS', N'Blanket Purchase Agreements — PRIFAS', N'MOCK12', N'SCM', N'PO', N'SCM_SUPPLIER_MOCK12_PRIFAS', N'SUP-PRIFAS', N'Supplier existence check — validations cross-reference supplier IDs against the Supplier header table to verify referenced suppliers exist', N'Not Loaded', N'Y', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VG_DEPENDENCIES_MOCK12 (Dependency_ID, Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module,  Depends_On_Table_Name, Depends_On_Validation_Group_ID, Dependency_Reason,  Dependency_Status, Blocks_Validation_Trigger,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'DEP-0012', N'BPA-SALUD', N'Blanket Purchase Agreements — SALUD', N'MOCK12', N'SCM', N'PO', N'SCM_SUPPLIER_MOCK12_SALUD', N'SUP-SALUD', N'Supplier existence check — validations cross-reference supplier IDs against the Supplier header table to verify referenced suppliers exist', N'Not Loaded', N'Y', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VG_DEPENDENCIES_MOCK12 (Dependency_ID, Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module,  Depends_On_Table_Name, Depends_On_Validation_Group_ID, Dependency_Reason,  Dependency_Status, Blocks_Validation_Trigger,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'DEP-0013', N'BPA-SIFDE', N'Blanket Purchase Agreements — SIFDE', N'MOCK12', N'SCM', N'PO', N'SCM_SUPPLIER_MOCK12_SIFDE', N'SUP-SIFDE', N'Supplier existence check — validations cross-reference supplier IDs against the Supplier header table to verify referenced suppliers exist', N'Not Loaded', N'Y', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VG_DEPENDENCIES_MOCK12 (Dependency_ID, Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module,  Depends_On_Table_Name, Depends_On_Validation_Group_ID, Dependency_Reason,  Dependency_Status, Blocks_Validation_Trigger,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'DEP-0014', N'CONT-SIFDE', N'Contracts — SIFDE', N'MOCK12', N'HCM', N'Core HR', N'SCM_SUPPLIER_MOCK12_SIFDE', N'SUP-SIFDE', N'Supplier existence check — validations cross-reference supplier IDs against the Supplier header table to verify referenced suppliers exist', N'Not Loaded', N'Y', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VG_DEPENDENCIES_MOCK12 (Dependency_ID, Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module,  Depends_On_Table_Name, Depends_On_Validation_Group_ID, Dependency_Reason,  Dependency_Status, Blocks_Validation_Trigger,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'DEP-0015', N'PO-911', N'Purchase Orders — 911', N'MOCK12', N'SCM', N'PO', N'SCM_SUPPLIER_MOCK12_911', N'SUP-911', N'Supplier existence check — validations cross-reference supplier IDs against the Supplier header table to verify referenced suppliers exist', N'Not Loaded', N'Y', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VG_DEPENDENCIES_MOCK12 (Dependency_ID, Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module,  Depends_On_Table_Name, Depends_On_Validation_Group_ID, Dependency_Reason,  Dependency_Status, Blocks_Validation_Trigger,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'DEP-0016', N'PO-ASSMCA', N'Purchase Orders — ASSMCA', N'MOCK12', N'SCM', N'PO', N'SCM_SUPPLIER_MOCK12_ASSMCA', N'SUP-ASSMCA', N'Supplier existence check — validations cross-reference supplier IDs against the Supplier header table to verify referenced suppliers exist', N'Not Loaded', N'Y', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VG_DEPENDENCIES_MOCK12 (Dependency_ID, Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module,  Depends_On_Table_Name, Depends_On_Validation_Group_ID, Dependency_Reason,  Dependency_Status, Blocks_Validation_Trigger,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'DEP-0017', N'PO-FIMAS', N'Purchase Orders — FIMAS', N'MOCK12', N'SCM', N'PO', N'SCM_SUPPLIER_MOCK12_FIMAS', N'SUP-FIMAS', N'Supplier existence check — validations cross-reference supplier IDs against the Supplier header table to verify referenced suppliers exist', N'Not Loaded', N'Y', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VG_DEPENDENCIES_MOCK12 (Dependency_ID, Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module,  Depends_On_Table_Name, Depends_On_Validation_Group_ID, Dependency_Reason,  Dependency_Status, Blocks_Validation_Trigger,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'DEP-0018', N'PO-HACIENDA', N'Purchase Orders — HACIENDA', N'MOCK12', N'SCM', N'PO', N'SCM_SUPPLIER_MOCK12_HACIENDA', N'SUP-HACIENDA', N'Supplier existence check — validations cross-reference supplier IDs against the Supplier header table to verify referenced suppliers exist', N'Not Loaded', N'Y', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VG_DEPENDENCIES_MOCK12 (Dependency_ID, Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module,  Depends_On_Table_Name, Depends_On_Validation_Group_ID, Dependency_Reason,  Dependency_Status, Blocks_Validation_Trigger,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'DEP-0019', N'PO-PRIFAS', N'Purchase Orders — PRIFAS', N'MOCK12', N'SCM', N'PO', N'SCM_SUPPLIER_MOCK12_PRIFAS', N'SUP-PRIFAS', N'Supplier existence check — validations cross-reference supplier IDs against the Supplier header table to verify referenced suppliers exist', N'Not Loaded', N'Y', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VG_DEPENDENCIES_MOCK12 (Dependency_ID, Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module,  Depends_On_Table_Name, Depends_On_Validation_Group_ID, Dependency_Reason,  Dependency_Status, Blocks_Validation_Trigger,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'DEP-0020', N'PO-SALUD', N'Purchase Orders — SALUD', N'MOCK12', N'SCM', N'PO', N'SCM_SUPPLIER_MOCK12_SALUD', N'SUP-SALUD', N'Supplier existence check — validations cross-reference supplier IDs against the Supplier header table to verify referenced suppliers exist', N'Not Loaded', N'Y', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VG_DEPENDENCIES_MOCK12 (Dependency_ID, Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module,  Depends_On_Table_Name, Depends_On_Validation_Group_ID, Dependency_Reason,  Dependency_Status, Blocks_Validation_Trigger,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'DEP-0021', N'PO-SIFDE', N'Purchase Orders — SIFDE', N'MOCK12', N'SCM', N'PO', N'SCM_SUPPLIER_MOCK12_SIFDE', N'SUP-SIFDE', N'Supplier existence check — validations cross-reference supplier IDs against the Supplier header table to verify referenced suppliers exist', N'Not Loaded', N'Y', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VG_DEPENDENCIES_MOCK12 (Dependency_ID, Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module,  Depends_On_Table_Name, Depends_On_Validation_Group_ID, Dependency_Reason,  Dependency_Status, Blocks_Validation_Trigger,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'DEP-0022', N'PROCONT-ASG', N'Procurement Contracts — ASG', N'MOCK12', N'SCM', N'Procurement Contract', N'SCM_SUPPLIER_MOCK12_ASG', N'SUP-ASG', N'Supplier existence check — validations cross-reference supplier IDs against the Supplier header table to verify referenced suppliers exist', N'Not Loaded', N'Y', N'phase4_seed', SYSUTCDATETIME());
INSERT INTO VG_DEPENDENCIES_MOCK12 (Dependency_ID, Validation_Group_ID, Validation_Group_Name, Mock_Number, Pillar, Module,  Depends_On_Table_Name, Depends_On_Validation_Group_ID, Dependency_Reason,  Dependency_Status, Blocks_Validation_Trigger,  Last_Updated_By, Last_Updated_DateTime) VALUES (N'DEP-0023', N'REQ-SIFDE', N'Requisition — SIFDE', N'MOCK12', N'SCM', N'PO', N'SCM_SUPPLIER_MOCK12_SIFDE', N'SUP-SIFDE', N'Supplier existence check — validations cross-reference supplier IDs against the Supplier header table to verify referenced suppliers exist', N'Not Loaded', N'Y', N'phase4_seed', SYSUTCDATETIME());
PRINT 'Seeded 23 VG_DEPENDENCIES_MOCK12 rows';
GO
