-- Auto-generated from Database_Schema_v9.xlsx → Schema Reference sheet
-- Idempotent: deletes Spec_Version='v9' rows first, then inserts.
USE [Hacienda_ERP_Test];
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'SCHEMA_REFERENCE')
BEGIN
    RAISERROR('SCHEMA_REFERENCE missing. Run phase1_migration.sql first.', 16, 1);
    RETURN;
END;

DELETE FROM SCHEMA_REFERENCE WHERE Spec_Version = N'v9';
PRINT 'Cleared previous v9 rows. Loading 63 rows...';

INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'AWS Files', N'AWS_eTag + Movement_Sequence', N'Composite PK', N'eTag (32-char hex) + Integer', N'Composite primary key. eTag identifies the S3 object; Movement_Sequence distinguishes each movement event.', N'Y', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'AWS Files', N'File_Category', N'Enum', N'Extract | Validation to Source | Conversion Load | Recon Report | Validation Before Load | Distribution - Extract | Distribution - Validation to Source | Distribution - Conversion Load | Distribution - Recon Report | Distribution - Validation Before Load', N'Type of file in the pipeline.', N'Y', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'AWS Files', N'Conversion_Plan_Table_Name', N'Text', N'Matches Table_Name in Conversion Plan', N'FK → Conversion Plan. Populated for Extract files. Null for Validation to Source, Conversion Load, Recon, VBL files.', N'N', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'AWS Files', N'Conversion_Plan_Entity', N'Text', N'Matches Entity in Conversion Plan', N'FK at entity level. Populated for all file categories — the entity this file relates to.', N'Y', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'AWS Files', N'Validation_Group_ID', N'Text', N'Matches Validation_Group_ID', N'FK → Validation Groups. Populated for Extract and Validation to Source files.', N'N', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'AWS Files', N'VBL_Group_ID', N'Text', N'Matches VBL_Group_ID', N'FK → VBL Groups. Populated for Conversion Load, Recon Report, VBL, and Distribution files.', N'N', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'AWS Files', N'File_Status', N'Enum', N'Received | Gate Check Running | Invalid File Name | File Not Expected | Invalid Headers | TSQL Load File Not Found | TSQL Load Error | Table Load Success | Validation Running | Validation Failed | Pending Approval | Approved | Rejected | Pending VBL Approval | Sent to Oracle | Distributed | Superseded | Archived', N'Status of this specific file+movement row.', N'Y', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'AWS Files', N'Error_Type', N'Enum', N'None | Invalid File Name | File Not Expected | Invalid Headers | TSQL Load File Not Found | TSQL Load Error', N'Specific error causing failure. None when clean.', N'Y', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'AWS Files', N'Error_Owner', N'Enum', N'None | Source Team | Pipeline Team', N'Source Team owns gate check failures. Pipeline Team owns TSQL errors.', N'Y', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'AWS Files', N'Supersedes_eTag', N'Text', N'eTag or blank', N'eTag of prior upload this file replaces.', N'N', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'AWS Files', N'Superseded_By_eTag', N'Text', N'eTag or blank', N'eTag of newer upload that replaced this file.', N'N', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'AWS Files', N'Split_From_eTag', N'Text', N'eTag or blank', N'eTag of consolidated parent file this BU-split file was derived from.', N'N', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'AWS Files', N'Sterling_Transmission_Status', N'Enum', N'Not Submitted | Submitted | Error | null', N'Populated only for Conversion Load files. Updated when file is transmitted to Deloitte via Sterling. No new S3 event — status update only.', N'N', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'AWS Files', N'Sterling_Transmission_DateTime', N'DateTime', N'MM/DD/YYYY HH:MM', N'When Sterling transmission occurred.', N'N', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'Validation Groups', N'Validation_Group_ID', N'Text PK', N'e.g. APINV-PRIFAS', N'Primary key. Groups the Extract files that must all reach Table Load Success before validation triggers.', N'Y', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'Validation Groups', N'Members_Total', N'Number', N'Integer', N'Total Extract tables in this group per Conversion Plan.', N'Y', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'Validation Groups', N'Members_Currently_Loaded', N'Number', N'Integer', N'Count of members currently at Table Load Success in ConversionFiles. Increments independently as each file loads. When equals Members_Total, validation auto-triggers.', N'Y', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'Validation Groups', N'All_Members_Loaded', N'Enum', N'Y | N', N'Y when Members_Currently_Loaded = Members_Total. Triggers new validation run.', N'Y', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'Validation Groups', N'Error_Threshold', N'Number', N'Integer', N'Maximum acceptable error count. If Validation Run Error_Count exceeds this, Threshold_Exceeded = Y and re-extract is required.', N'Y', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'Validation Groups', N'Revalidation_Triggered_By_eTag', N'Text', N'eTag', N'The specific file upload that caused the latest validation run to trigger (either by completing the group for first run, or by re-uploading after approval).', N'N', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'Validation Runs', N'Validation_Run_ID', N'Text PK', N'VAL-NNNN', N'Primary key. One row per validation run per group.', N'Y', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'Validation Runs', N'Run_Number', N'Number', N'Integer >= 1', N'Sequential run number for this Validation_Group_ID. First run = 1.', N'Y', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'Validation Runs', N'Trigger_Reason', N'Enum', N'Initial Load | Re-upload | Manual Trigger', N'Why this run was triggered.', N'Y', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'Validation Runs', N'Triggered_By_eTag', N'Text', N'eTag', N'The file upload whose Table Load Success completed the group and triggered this run.', N'Y', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'Validation Runs', N'Error_Count', N'Number', N'Integer', N'Errors found — issues that prevent records from converting.', N'N', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'Validation Runs', N'Warning_Count', N'Number', N'Integer', N'Warnings found — data quality issues that do not block conversion.', N'N', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'Validation Runs', N'Informative_Record_Count', N'Number', N'Integer', N'Record count and summary statistics from the informative section of the validation output.', N'N', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'Validation Runs', N'Threshold_Exceeded', N'Enum', N'Y | N', N'Y when Error_Count > Error_Threshold defined on the Validation Group.', N'Y', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'Validation Runs', N'Reextract_Required', N'Enum', N'Y | N', N'Y when approver determines errors require source re-extract. Triggers File_Expected reset for affected members.', N'Y', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'Validation Runs', N'Affected_Members', N'Text', N'Semicolon-separated Table_Names', N'Which specific table members had errors requiring re-extract. Used to target File_Expected resets.', N'N', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'Validation Runs', N'Validation_File_eTag', N'Text', N'eTag', N'FK → AWS Files. The eTag of the Validation to Source Excel output file generated by this run.', N'N', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'VBL Groups', N'VBL_Group_ID', N'Text PK', N'e.g. VBL-FIN-AP', N'Primary key. Groups the Validation to Source groups that must all be approved before VBL run triggers.', N'Y', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'VBL Groups', N'Val_To_Source_Members_Total', N'Number', N'Integer', N'Total Validation Groups required for this VBL Group per VBL Group Members mapping table.', N'Y', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'VBL Groups', N'Val_To_Source_Members_Approved', N'Number', N'Integer', N'Count of required Validation Groups currently at Approval_Status = Approved.', N'Y', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'VBL Groups', N'All_Val_To_Source_Approved', N'Enum', N'Y | N', N'Y when all required Validation Groups are approved. Triggers Conversion Load, Recon Report, and VBL file generation.', N'Y', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'VBL Groups', N'Sterling_Transmission_Status', N'Enum', N'Not Submitted | Submitted | Error', N'Status of Deloitte Sterling transmission for the Conversion Load file. No separate S3 event — status update only.', N'N', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'VBL Group Members', N'VBL_Group_ID + Validation_Group_ID', N'Composite PK', N'—', N'Composite primary key of the mapping table.', N'Y', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'VBL Group Members', N'Required', N'Enum', N'Y | N', N'Y = this Validation Group must be approved before the VBL Group can trigger.', N'Y', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'VBL Group Members', N'Blocks_VBL_Trigger', N'Enum', N'Y | N', N'Y when this member is Required = Y and not yet approved. Derived field — useful for dashboard filtering.', N'Y', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'Business Rules', N'File_Category enum', N'—', N'Extract | Validation to Source | Conversion Load | Recon Report | Validation Before Load | Distribution - Extract | Distribution - Validation to Source | Distribution - Conversion Load | Distribution - Recon Report | Distribution - Validation Before Load', N'Complete list of file categories. No Log category. Sterling transmission is a status update on an existing Conversion Load row, not a new file event.', N'—', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'Business Rules', N'Validation to Source trigger', N'—', N'All group members reach Table Load Success', N'Members_Currently_Loaded = Members_Total sets All_Members_Loaded = Y and auto-triggers a new Validation Run. This applies both for initial load and re-uploads post-approval (re-validation).', N'—', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'Business Rules', N'Re-validation trigger', N'—', N'Any group member re-uploads after approval', N'When File_Expected is reset to Y and a new upload reaches Table Load Success, the system checks All_Members_Loaded. Since other members are already in ConversionFiles, it is immediately Y → new Validation Run triggers automatically.', N'—', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'Business Rules', N'Error threshold & re-extract', N'—', N'Error_Count > Error_Threshold → Reextract_Required = Y', N'When threshold is exceeded, approver rejects the run and sets File_Expected = Y on the Affected_Members. New uploads for those members trigger re-validation.', N'—', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'Business Rules', N'VBL trigger', N'—', N'All required Validation Groups in VBL Group Members approved', N'All_Val_To_Source_Approved = Y triggers: Conversion Load file generation, Recon Report generation, and VBL file generation. Blocks_VBL_Trigger = Y on any member means VBL cannot proceed.', N'—', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'Business Rules', N'Sterling transmission', N'—', N'Status update only — no new S3 event', N'When VBL is approved, the existing Conversion Load AWS Files row is updated: Sterling_Transmission_Status = Submitted, File_Status = Sent to Oracle. No new file or row is created.', N'—', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'Business Rules', N'Distribution files', N'—', N'Split_From_eTag links to consolidated parent', N'Distribution files are BU splits of approved consolidated files. Split_From_eTag points to the parent. One distribution file per BU per source file.', N'—', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'AWS Files', N'Check_File_Expected', N'Enum', N'Pass / Fail / Not Run / N/A', N'Gate check 2 of 5. Verifies File_Expected = Y in Conversion Plan. Runs only if Check_File_Name = Pass. If Fail → all subsequent checks set to Not Run. N/A for non-Extract files and seq 2 rows.', N'Y for Extract seq 1', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'AWS Files', N'Check_File_Name', N'Enum', N'Pass / Fail / Not Run / N/A', N'Gate check 1 of 5. Extract seq 1 only. Verifies file name matches expected naming convention. If Fail → all subsequent checks set to Not Run, file moved to Errors immediately. N/A for non-Extract files and seq 2 rows.', N'Y for Extract seq 1', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'AWS Files', N'Check_Column_Headers', N'Enum', N'Pass / Fail / Not Run / N/A', N'Gate check 3 of 5. Verifies column headers match expected schema for this Conversion Plan table. Runs only if Check_File_Expected = Pass. N/A for non-Extract files and seq 2 rows.', N'Y for Extract seq 1', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'AWS Files', N'Check_TSQL_File_Found', N'Enum', N'Pass / Fail / Not Run / N/A', N'Gate check 4 of 5. Verifies the TSQL stored procedure can locate the file. Runs only if Check_Column_Headers = Pass. Pipeline Team owns resolution if Fail. N/A for non-Extract files and seq 2 rows.', N'Y for Extract seq 1', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'AWS Files', N'Check_TSQL_Load', N'Enum', N'Pass / Fail / Not Run / N/A', N'Gate check 5 of 5. Verifies TSQL load executed successfully. Runs only if Check_TSQL_File_Found = Pass. Pipeline Team owns resolution if Fail. N/A for non-Extract files and seq 2 rows.', N'Y for Extract seq 1', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'Business Rules', N'Gate Check Sequence', N'—', N'Check_File_Name → Check_File_Expected → Check_Column_Headers → Check_TSQL_File_Found → Check_TSQL_Load', N'Checks run in strict order for Extract files seq 1 only. Pass = check ran and passed. Fail = check ran and failed (file moved to Errors). Not Run = check was skipped because a prior check failed. N/A = gate checks do not apply to this file (non-Extract category or seq 2 row). Error_Type on File Lifecycle mirrors the failed check name for quick filtering.', N'—', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'VG Dependencies', N'Dependency_ID', N'Text PK', N'DEP-NNNN', N'Primary key.', N'Y', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'VG Dependencies', N'Validation_Group_ID', N'Text FK', N'Matches Validation_Group_ID', N'The group that has the dependency — cannot trigger validation until dependency is satisfied.', N'Y', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'VG Dependencies', N'Depends_On_Table_Name', N'Text', N'Matches Table_Name in Conversion Plan', N'Specific table that must be at Table Load Success before the dependent group can trigger. Currently all Supplier header tables: SCM_SUPPLIER_MOCK12_{SOURCE}.', N'Y', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'VG Dependencies', N'Depends_On_Validation_Group_ID', N'Text FK', N'Matches Validation_Group_ID', N'The group that owns the required table.', N'Y', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'VG Dependencies', N'Dependency_Status', N'Enum', N'Loaded / Not Loaded', N'Loaded when Depends_On_Table_Name has an active Table Load Success row in AWS Files.', N'Y', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'VG Dependencies', N'Blocks_Validation_Trigger', N'Enum', N'Y / N', N'Y when Dependency_Status = Not Loaded. Validation will not fire while any dependency row for the group has Blocks_Validation_Trigger = Y.', N'Y', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'Business Rules', N'Full Validation Trigger Rule', N'—', N'Members_Currently_Loaded = Members_Total AND all VG Dependencies rows have Blocks_Validation_Trigger = N', N'Both conditions required. Own members loaded AND all cross-group dependency tables loaded.', N'—', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'Business Rules', N'Retiro descoped', N'—', N'All Retiro rows deleted', N'Retiro removed from all entities: AR Customer, AR Invoices, GL Balances, GL Budget Balances, PS Items, Blanket Purchase Agreements, Purchase Orders, Buyer, Awards, Setup.', N'—', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'Business Rules', N'DOE renamed to SIFDE', N'—', N'Source DOE = SIFDE', N'Contracts entity source DOE corrected to SIFDE. Table name updated to HCM_CONTRACT_MOCK12_SIFDE.', N'—', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'Business Rules', N'VG ID Convention', N'—', N'APINV | PO | BPA | REQ | PROCONT | CONT | SUP — all suffixed with -{SOURCE}', N'Naming convention for all Validation Group IDs. Prefix = entity type, suffix = source system in uppercase.', N'—', N'v9');
INSERT INTO SCHEMA_REFERENCE (Sheet, Column_Field, Data_Type, Allowed_Values, Description, Required, Spec_Version) VALUES (N'Business Rules', N'ASG Supplier', N'—', N'SCM_SUPPLIER_MOCK12_ASG added', N'Supplier header table added to SUP-ASG group so ASG-sourced entities (PROCONT-ASG) can declare the Supplier dependency.', N'—', N'v9');

PRINT 'SCHEMA_REFERENCE seeded.';
GO
